version: '3.8'
services:
    server:
        build:
            dockerfile: Dockerfile.dev
            context: .
        volumes:
            - .:/app
        depends_on:
            - db
            - redis
    db:
        image: postgres:14-alpine
        container_name: db
        ports:
            - "5432:5432"
            # host:container
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=db
    redis:
        image: redis:latest
        container_name: redis
        ports:
        - "6379:6379"
        volumes:
        - redis-data:/data
volumes:
    redis-data:
        driver: local